# Generated by Django 4.0.2 on 2022-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=100)),
                ('reg_id', models.IntegerField(max_length=5)),
                ('phone_number', models.BigIntegerField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
