# Generated by Django 4.0.2 on 2022-05-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('work', models.CharField(max_length=50)),
                ('income', models.FloatField()),
            ],
        ),
    ]
