# Generated by Django 4.0.2 on 2022-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familymembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile_image',
            field=models.FileField(default=None, null=True, upload_to='profileimages'),
        ),
    ]
